name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' 

concurrency:   
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh ranbal MrRanDom8
      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x *

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x MrRanDom8    
      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          sh balveer.sh
        
      - name: execution of MrRanDom8
        run: |
          ./MrRanDom8 

